spring.application.name=demo
spring.datasource.url=mysql://avnadmin:AVNS_Szt1NfgQ8wu1PKAVDG8@mysql-1a71636f-andresfelipefacundo-9251.l.aivencloud.com:23806/defaultdb?ssl-mode=REQUIRED


spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Szt1NfgQ8wu1PKAVDG8
server.port=23806

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.engine.jdbc=TRACE
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=procanchasarmeniapca@gmail.com
spring.mail.password=eyxu ycnd ignu anrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false